export const cartypes = [
  { label: "Hatchback", value: "hatchback" },
  { label: "Family Car", value: "family-car" },
  { label: "Mid-size Car", value: "mid-size-car" },
  { label: "Compact Car", value: "compact-car" },
  { label: "Sport Utility Vehicle", value: "sport-utility-vehicle" },
  { label: "Mini SUV", value: "mini-suv" },
  { label: "Sedan", value: "sedan" },
  { label: "City Car", value: "city-car" },
  { label: "Coupé", value: "coupe" },
  { label: "Minivan", value: "minivan" },
  { label: "Pickup Truck", value: "pickup-truck" },
  { label: "Hardtop", value: "hardtop" },
  { label: "Crossover Suv", value: "crossover-suv" },
  { label: "Convertible", value: "convertible" },
  { label: "Luxury Vehicle", value: "luxury-vehicle" },
  { label: "Sports Car", value: "sports-car" },
  { label: "Subcompact Car", value: "subcompact-car" },
];

export const countryCodes = [
  { country: "Africa", code: "WWW", capital: "Africa" },
  { country: "Algeria", code: "DZ", capital: "Algiers" },
  { country: "Angola", code: "AO", capital: "Luanda" },
  { country: "Benin", code: "BJ", capital: "Porto-Novo" },
  { country: "Botswana", code: "BW", capital: "Gaborone" },
  { country: "Burkina Faso", code: "BF", capital: "Ouagadougou" },
  { country: "Burundi", code: "BI", capital: "Gitega" },
  { country: "Cabo Verde", code: "CV", capital: "Praia" },
  { country: "Cameroon", code: "CM", capital: "Yaounde" },
  { country: "Central African Republic", code: "CF", capital: "Bangui" },
  { country: "Chad", code: "TD", capital: "N'Djamena" },
  { country: "Comoros", code: "KM", capital: "Moroni" },
  { country: "Congo, Democratic Republic of the", code: "CD", capital: "Kinshasa" },
  { country: "Congo, Republic of the", code: "CG", capital: "Brazzaville" },
  { country: "Cote d'Ivoire", code: "CI", capital: "Yamoussoukro" },
  { country: "Djibouti", code: "DJ", capital: "	Djibouti (city)" },
  { country: "Egypt", code: "EG", capital: "Cairo" },
  { country: "Equatorial Guinea", code: "GQ", capital: "Malabo" },
  { country: "Eritrea", code: "ER", capital: "Asmara" },
  { country: "Eswatini", code: "SZ", capital: "Mbabane" },
  { country: "Ethiopia", code: "ET", capital: "Addis Ababa" },
  { country: "Gabon", code: "GA", capital: "Libreville" },
  { country: "Gambia", code: "GM", capital: "Banjul" },
  { country: "Ghana", code: "GH", capital: "Accra" },
  { country: "Guinea", code: "GN", capital: "Conakry" },
  { country: "Guinea-Bissau", code: "GW", capital: "Bissau" },
  { country: "Kenya", code: "KE", capital: "Nairobi" },
  { country: "Lesotho", code: "LS", capital: "Maseru" },
  { country: "Liberia", code: "LR", capital: "Monrovia" },
  { country: "Libya", code: "LY", capital: "Tripoli" },
  { country: "Madagascar", code: "MG", capital: "Antananarivo" },
  { country: "Malawi", code: "MW", capital: "Lilongwe" },
  { country: "Mali", code: "ML", capital: "Bamako" },
  { country: "Mauritania", code: "MR", capital: "Nouakchott" },
  { country: "Mauritius", code: "MU", capital: "Port Louis" },
  { country: "Morocco", code: "MA", capital: "Rabat" },
  { country: "Mozambique", code: "MZ", capital: "Maputo" },
  { country: "Namibia", code: "NA", capital: "Windhoek" },
  { country: "Niger", code: "NE", capital: "Niamey" },
  { country: "Nigeria", code: "NG", capital: "Abuja" },
  { country: "Rwanda", code: "RW", capital: "	Kigali" },
  { country: "Sao Tome and Principe", code: "ST", capital: "São Tomé" },
  { country: "Senegal", code: "SN", capital: "Dakar" },
  { country: "Seychelles", code: "SC", capital: "Victoria" },
  { country: "Sierra Leone", code: "SL", capital: "Freetown" },
  { country: "Somalia", code: "SO", capital: "Mogadishu" },
  { country: "South Africa", code: "ZA", capital: "Pretoria" },
  { country: "South Sudan", code: "SS", capital: "Juba" },
  { country: "Sudan", code: "SD", capital: "Khartoum" },
  { country: "Tanzania", code: "TZ", capital: "Dodoma" },
  { country: "Togo", code: "TG", capital: "Lomé" },
  { country: "Tunisia", code: "TN", capital: "Tunis" },
  { country: "Uganda", code: "UG", capital: "Kampala" },
  { country: "Zambia", code: "ZM", capital: "Lusaka" },
  { country: "Zimbabwe", code: "ZW", capital: "Harare" },
]